

SET SERVEROUTPUT ON;


CREATE TABLE FACULTY(
   F_ID NUMBER(10) UNIQUE ,
   Fa_Name VARCHAR2(20)  PRIMARY KEY ,
   MOB_NUMBER NUMBER (10)   UNIQUE

);


SELECT * FROM FACULTY;


CREATE TABLE DEPARTMENT(
     DE_ID NUMBER(20) UNIQUE,
     DE_Name VARCHAR2(20) PRIMARY KEY,
     Fa_Name VARCHAR2(20),
     
     
     CONSTRAINT  FK_DEPARTMENT
     FOREIGN KEY (Fa_Name)
     REFERENCES FACULTY(Fa_Name)
 );
    
   SELECT * FROM DEPARTMENT;


     
CREATE TABLE TEACHER(
     T_ID NUMBER(20) PRIMARY KEY,
     F_Name VARCHAR2(20) NOT NULL ,
     L_Name VARCHAR2(20),
     Phone  NUMBER(20) UNIQUE,
     Email VARCHAR2(40) UNIQUE,
     Addras VARCHAR2(50),
     Gander VARCHAR2(4),
     Salary NUMBER(10),
     Ssn  NUMBER(10) UNIQUE ,
     DE_Name VARCHAR2(20) ,
    
    
     CONSTRAINT  FK_TEACHER
     FOREIGN KEY (DE_NamE)
     REFERENCES DEPARTMENT(DE_Name)

);   


SELECT * FROM TEACHER;




CREATE TABLE EMPLOYEE(
     E_ID NUMBER(10) PRIMARY KEY,
     F_Name VARCHAR2(20) NOT NULL ,
     L_Name VARCHAR2(20),
     Phone  NUMBER(10) UNIQUE ,
     Email VARCHAR2(40) UNIQUE ,
     Addras VARCHAR2(50),
     Gander CHAR,
     Salary NUMBER(7),
     Ssn  NUMBER(10) UNIQUE ,
     Job VARCHAR2(20) NOT NULL,
     DE_Name VARCHAR2(20) ,
     
     CONSTRAINT  FK_EMPLOYEE
     FOREIGN KEY (DE_Name)
     REFERENCES DEPARTMENT(DE_Name)
     
);     


SELECT * FROM EMPLOYEE;



CREATE TABLE CLASS (
     C_ID  NUMBER(10) PRIMARY KEY,
     Name VARCHAR2(20) UNIQUE,
     DE_Name VARCHAR2(20) ,
     
     CONSTRAINT  FK_CLASS
     FOREIGN KEY (DE_Name)
     REFERENCES DEPARTMENT(DE_Name)
);


SELECT * FROM CLASS;


CREATE TABLE SEMESTER(
     S_ID  NUMBER(10) PRIMARY KEY,
     Name VARCHAR2(20) UNIQUE,
     C_ID NUMBER(10) ,
     
     CONSTRAINT  FK_SEMESTER
     FOREIGN KEY (C_ID)
     REFERENCES CLASS(C_ID)
);



SELECT * FROM SEMESTER;


CREATE TABLE SUBJECT (
     Sub_ID  NUMBER(10) PRIMARY KEY,
     Name  VARCHAR2(20),
     S_ID  NUMBER(10) ,
     T_ID  NUMBER(10) ,
     
     CONSTRAINT  FK_SUBJECT
     FOREIGN KEY (S_ID)
     REFERENCES SEMESTER(S_ID),
     
     CONSTRAINT  FK_SUBJECTT
     FOREIGN KEY (T_ID)
     REFERENCES TEACHER(T_ID) 

);
alter table subject add credit number(1);


SELECT * FORM SUBJECT;




CREATE TABLE STUDENT (
    Stu_ID NUMBER(10) PRIMARY KEY,
    F_Name VARCHAR2(20) NOT NULL,
    L_Name VARCHAR2(20),
    Fname  VARCHAR2(20),
    Phone  NUMBER(10) UNIQUE,
    Email  VARCHAR2(40) UNIQUE,
    Addras  VARCHAR2(50),
    Gander  VARCHAR2(10),
    Ssn  NUMBER(10) UNIQUE ,
    S_ID  NUMBER(10) ,
    DE_Name VARCHAR2(20) ,
    
    CONSTRAINT  FK_STUDENT
     FOREIGN KEY (DE_Name)
     REFERENCES DEPARTMENT(DE_Name),
     
     CONSTRAINT  FK_STUDENTF
     FOREIGN KEY (S_ID)
     REFERENCES SEMESTER(S_ID)
     
);


SELECT * FROM STUDENT ;



CREATE TABLE MARKES (
    Stu_ID NUMBER(10) ,
    Sub_ID NUMBER(10) ,
    LENGHT NUMBER (3),
    
    CONSTRAINT  FK_MARKESSTU
     FOREIGN KEY (Stu_ID)
     REFERENCES STUDENT(Stu_ID),
     
     CONSTRAINT  FK_MARKESSUB
     FOREIGN KEY (Sub_ID)
     REFERENCES SUBJECT(Sub_ID)
);


SELECT * FROM MARKES ;


CREATE TABLE WORK_ON(
    DAY_WORK DATE ,
     HOURS NUMBER(3),
     E_ID NUMBER ,
     DE_Name,
     
     CONSTRAINT  FK_WORK_OF_EM
     FOREIGN KEY (E_ID)
     REFERENCES EMPLOYEE(E_ID),
     
     
     CONSTRAINT  FK_WORK_ON_D
     FOREIGN KEY (DE_Name)
     REFERENCES DEPARTMENT(DE_Name)
);


SELECT * FROM WORK_ON;




